version: '3'

services:
  spark:
    image: docker.io/bitnami/spark:3
    container_name: spark-master
    env_file:
      - config/spark_master.env
    ports:
      - '8080:8080'
    volumes:
      - shared/:/opt/workspace

  spark-worker-1:
    container_name: spark-worker-1
    image: docker.io/bitnami/spark:3
    env_file:
      - config/worker_1.env
    ports:
      - '8081:8081'
    volumes:
      - shared/:/opt/workspace
    depends_on:
      - spark

  spark-worker-2:
    container_name: spark-worker-2
    image: docker.io/bitnami/spark:3
    env_file:
      - config/worker_2.env
    ports:
      - '8082:8082'
    volumes:
      - shared/:/opt/workspace
    depends_on:
      - spark

volumes:
  shared:
